config/routes.rb
Rails.application.routes.draw do
  root to: "histories#index"
  
  resources :poems
  resources :histories, only: %w{index}
  
  post '/quiz', to: 'quiz#resolve'
  post '/registration', to: 'quiz#regisration'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :poem, dependent: :destroy
  
  scope :find_title, -> (question){ joins(:poem).where(text: question).limit(1).pluck("title").join }
  scope :find_line_with_skipped_word, -> (query_part_of_words){ where("text like #{ query_part_of_words }").pluck("text") }
  scope :find_changed_word_and_original, -> (query_part){ where("text like #{ query_part.join("OR text like") }").pluck("text") }
  scope :find_text_with_correct_letters, -> (query_part_of_letters){ where("text like #{ query_part_of_letters }").limit(1) }
  scope :find_correct_text, -> (line_id){ joins(:poem).where(id: line_id).pluck("text").join }
  scope :find_sorted_string, -> (question){ joins(:poem).where(sorted_line: question).pluck("text").join }
  scope :find_sorted_string_by_parts, -> (query_part){ where("sorted_line like #{ query_part }").pluck("text").join  }
end

app/models/line_symbol.rb
class LineSymbol < ApplicationRecord
  belongs_to :line
end

app/models/poem.rb
class Poem < ApplicationRecord
  has_many :lines, dependent: :destroy 
  belongs_to :quiz
  def lines
    Line.where(poem_id: self.id).pluck("text").join("\r\n")
  end

end

app/models/quiz.rb
class Quiz < ApplicationRecord

end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :line
  
  scope :fifth_level, -> (words){select("line_id").where(text: words).group(:line_id).having("count(*) > 2").order("count(*) desc").limit(1).pluck("line_id").join}
  scope :take_line_id, -> (line_id){where(line_id: line_id).pluck("text")}

end

app/controllers/concerns/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
	def index
		@histories = History.all	
	end
	
	def new
		@history = History.new	
	end
	
	def create
		@history = History.new(history_params)
	end
	
	private	
	
	def history_params
		params.require(:history).permit(:question, :answer, :level)	
	end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]

  include PoemsHelper

  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.all
  end
  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    @poem = Poem.new(poem_params)  
    @poem_lines = params[:poem][:lines].split("\r\n") # poem lines

    respond_to do |format|
      if @poem.save && save_poem_lines(Poem.last.id, @poem_lines)
        
        format.html { redirect_to @poem, notice: 'Poem was successfully created.' }
      else
        format.html { render :new }
      end
    end
    
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'Poem was successfully destroyed.' }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:title)
    end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  include QuizResolver

  skip_before_action :verify_authenticity_token
  
  ADDR=URI("http://pushkin.rubyroidlabs.com/quiz") 
  
  def resolve
		render json: 'ok' 
    
    question = params['question']
    level = params['level']
    answer = q_resolve level, question
 
    parameters = {
      answer: answer,
      token: Rails.application.secrets[:api_key],
      task_id:  params[:id]
    }

    Net::HTTP.post_form(ADDR, parameters)

    History.new(answer: answer, question: question, level: level).save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
  def poem_lines(poem_id)
    Line.where(poem_id: poem_id).pluck("text")
  end
  
  def save_poem_lines(poem_id, poem_lines)
    Line.bulk_insert do |lines| # using gem bulk_insert
      poem_lines.map do |text|
        total_matches = 0
        text.chars.each do |symbol|
        end  
        lines.add({poem_id: poem_id, text: text, sorted_line: text.chars.sort.join.gsub(/[^0-9А-Яа-я]/i, '')})
      end
    end

    lines = Line.where(poem_id: poem_id)
    save_lines_words(lines)
    save_lines_symbols(lines)
    true
  end

  private
  
  def save_lines_words(lines)
    Word.bulk_insert do |words| # using gem bulk_insert
      lines.map do |line|
        line.text.split(/[^[[:word:]]]+/).delete_if(&:blank?).map do |text|
          words.add({line_id: line.id, text: text})
        end
      end
    end
  end

  def save_lines_symbols(lines)

  end
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/histories/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Level</th>
      <th>Question</th>
      <th>Answer</th>
    </tr>
  </thead>
  <tbody>
		<% @histories.each do |history| %>
    <tr>
      <th scope="row"><%= history.id %></th>
      <td><%= history.level %></td>
      <td><%= history.question %></td>
      <td><%= history.answer %></td>
    </tr>
		<% end%>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PushkinResolver</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/poems/_form.html.erb
<%= form_for(poem) do |f| %>
  <% if poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% poem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %></br>
    <%= f.text_area :lines, size: "70x20" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/edit.html.erb
<h1>Editing Poem</h1>

<%= render 'form', poem: @poem %>

<%= link_to 'Show', @poem %> |
<%= link_to 'Back', poems_path %>

app/views/poems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poems</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Lines</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poems.each do |poem| %>
      <tr>
        <td><%= poem.id %></td>
        <td><%= poem.title %></td>
        <td>
          <% poem_lines(poem.id).first(3).map do |line|%>
            <%= line %></br>
          <% end %>
          <%= "..." %></br>
        </td>
        <td><%= link_to 'Show', poem %></td>
        <td><%= link_to 'Edit', edit_poem_path(poem) %></td>
        <td><%= link_to 'Destroy', poem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poem', new_poem_path %>

app/views/poems/new.html.erb
<h1>New Poem</h1>

<%= render 'form', poem: @poem %>

<%= link_to 'Back', poems_path %>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong></br>
  <%= @poem.title %>
</p>

<strong>Lines:</strong></br>
  
<% poem_lines(params[:id]).each do |line|%>
  <%= line %></br>
<% end %></br>

<%= link_to 'Edit', edit_poem_path(@poem) %> |
<%= link_to 'Back', poems_path %>